spring.application.name=contactsManager

#MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/contactsManager_db?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show.show-sql=true

jwt.secret=a0f924ae7dc1de50a1195ef3efe096a5
jwt.expiration-ms=86400000